### PR TITLE
Renaming package 

### PR DESCRIPTION
**Pull request by freyac**
Per #8 , renaming package from `carbonplan_tonyear` to `tonyear`.

### CODE REVIEW

**Review by badgley — COMMENTED** [review]
:shipit:

**Comment by jhamman** [comment]
@freyac - thanks for doing this. One question, one hot tip.

Q1: Do you import `carbonplan_tonyear` in either of the Jupyter notebooks in this repo? If so, those also need updating.

Hot tip: I noticed you closed #8 already. Not a biggy, but in the future, you can write in your PR comment "closes #8" or "fixes #8", GitHub will automatically close the issue when the PR is merged.

**Comment by badgley** [comment]
@jhamman  

> Q1: Do you import `carbonplan_tonyear` in either of the Jupyter notebooks in this repo? If so, those also need updating.
> 

I checked this in my review. We're good to go!!

**Review by jhamman — APPROVED** [review]

**Comment by freyac** [comment]
Hot tip! Thanks, Joe :)

**Pull request merged**
