### PR TITLE
Mc equivalency notebook

### PR DESCRIPTION
**Pull request by freyac**
Created a notebook to demonstrate the physical mis-match of a Moura Costa equivalency claim.

### CODE REVIEW

**Comment by badgley** [comment]
independent of a code review, i was about to push a similarly named notebook (`mouracosta-equivalency`) demonstrating how longer storage periods under the MC method can justify the emission of more than 1 tCO2. im wondering if we should just have a single notebook?

**Review by badgley — COMMENTED** [review]
I added another MC example. Would you give the text a read to make sure everything checks out? Otherwise everything runs on my machine, it reads well, and makes sense to me.

**Review by badgley — COMMENTED** [review]
I added another MC example. Would you give the text a read to make sure everything checks out? Otherwise everything runs on my machine, it reads well, and makes sense to me.

**Comment by freyac** [comment]
Looks good, Grayson! Merging.

**Pull request merged**
